---
  detectors:
    IrresponsibleModule:
      enabled: false
    LongParameterList:
      exclude:
      - LeafAPI::Service::NTHUAPI#bus_schedule
  exclude_paths:
    - _snippets
    - lib/project_info.rb # one-time test fixture creator
